### ISSUE TITLE
cannot start device normally. (Failed to read data from device)

### ISSUE THREAD

**Issue by redkuoeys3d** [5VOXEL/voxel3d_tools#1]
Hi there, 

When I try to start 5voxel 3D camera,
it shows the fail message as below:
-------------------------
Found device (5Voxel 3D Camera)
camera parameters error
Failed to read data from device
-------------------------
my environment is windows 10, looking forward to your help.

Regards 
Andrew

**Comment by jackielee0424** [comment]
Hi Andrew,

It shall be that firmware on your camera is too old to support reading camera parameters. Please contact us (see contact info in [http://5voxel.com](http://5voxel.com)) to get support for firmware upgrade.
